### ISSUE TITLE
「High ground」の適切な和訳

### ISSUE THREAD

**Issue by 4sumi** [4sumi/RoN_jp_sub#2]
- 高知や狙撃犯ではないことは間違いない
- 求・有識者

**Comment by dynamiteOpanty** [comment]
https://www.merriam-webster.com/dictionary/high%20ground
これのような気がします　judgeのチームリーダーとしての"superior position"なのでは
しかしjudgeから"high ground"へ指示するボイスがある(PrefixHighGroundTeam_0)ので、結局よくわかりませんね

未実装の狙撃班がいるとして、普通のSWAT隊員への指示用に誤ってボイスが使用されているのかもしれません。推測でしかありませんが

**Comment by 4sumi** [comment]
コメントありがとうございます

（容疑者に対して道徳・権力的に/チーム内の指揮権が）高位に位置する者（のコールサイン）、という解釈はしっくりきますね

また別口で調べたところどうやら『SWAT4』に登場するヘリのコールサインが「ハイグラウンド」らしく、これのリスペクトである線もありますね

いずれにせよ、何かしらの意訳を当てるのではなく素直に「ハイグラウンド」としておくのが現状では丸く収まりそうです

後日狙撃班ないしそれに類する機能が実装されたらその際に修正します
